# Generated by Django 4.2.4 on 2023-09-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orer_quantity',
            new_name='order_quantity',
        ),
    ]
